version = 0.1

[default.global.parameters]
stack_name = "quizzapp-backend"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities        = "CAPABILITY_IAM"
confirm_changeset   = true
resolve_s3          = true
region              = "us-east-1"
disable_rollback    = false
s3_prefix = "quizzapp-backend"
parameter_overrides = [
  "BedrockRegion=us-east-1",
  "BedrockModelId=amazon.nova-pro-v1:0",
  "QdrantUrl=https://5ce163f1-18a2-49ca-a331-c5ac2b5b54da.sa-east-1-0.aws.cloud.qdrant.io",
  "StripeSecretKey=REPLACE_ME",
  "StripeWebhookSecret=REPLACE_ME",
  "StripePriceId=REPLACE_ME",
  "FrontendUrl=https://quizzapp.vercel.app",
]
image_repositories = []
